apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: database
  namespace: mariamnassar-dev
spec:
  source:
    git:
      uri: https://github.com/aalhabibi/event-planner-backend
    contextDir: mongodb
  strategy:
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: database:latest
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: database
  namespace: mariamnassar-dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  namespace: mariamnassar-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: database
        image: image-registry.openshift-image-registry.svc:5000/mariamnassar-dev/database:latest
        ports:
        - containerPort: 27015
        volumeMounts:
        - mountPath: /data/db
          name: mongo-data
      volumes:
      - name: mongo-data
        emptyDir: {} 
      securityContext:
        fsGroup: 999
---
apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: mariamnassar-dev
spec:
  selector:
    app: database
  ports:
  - port: 27015
    targetPort: 27015